### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by samoht**
Not sure why the tests are failing, though, as I got:

```
Testing dnssd.
[OK]                types                0   MX.
[ERROR]             types                1   No MX.
[OK]                errors               0   NXDomain.
[OK]                lowlevel             0   select.
[OK]                lowlevel             1   cancel.
[OK]                performance          0   1000.
[OK]                misc                 0   supported.
-- types.001 Failed --
No MX.
_build/_tests/types.001.output:
[failure] Error looking up records for dave.recoil.org: NoSuchRecord
```

### CODE REVIEW

**Comment by samoht** [comment]
Also are the tests not run on purpose by the CI? Could start an OSX worker instead of all these Linux machines :-)

**Comment by djs55** [comment]
I think I see that test fail intermittently on `master` too -- I'll investigate.

**Comment by samoht** [comment]
Thanks for fixing the tests! Should it be fine now to run these in TravisCI?

**Comment by djs55** [comment]
Yeah I think we should switch to running the tests (on OSX) if we can.

**Pull request merged**
